spring:
  datasource:
      url: jdbc:mysql://localhost:3306/ss?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(1x0NM8DOXUOUUj2TAyeVdA==)
      password: ENC(KX/8IiMgvSj1BBkXUvJU4JvuQRZoy8/6)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    # 连接设置
    database: 0 # Redis数据库索引（默认为0）
    host: ENC(WIT/NHqNNWQ8JYpv2oEty9t3ujsv5ikN)
    port: 6379
    password:
    timeout: 3000 # 连接超时时间（毫秒）
    jedis:
      # 连接池设置
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        max-wait: 3000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
mybatis:
  mapper-locations: classpath:mapper/*.xml # 所有的mapper映射文件
  type-aliases-package: com.ponmma.ss.entity # 定义所有操作类的别名所在包
  configuration:
    use-generated-keys: true # 使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-column-label: true # 使用列别名替换列名 默认:true
    map-underscore-to-camel-case: true # 开启驼峰命名转换:Table{create_time} -> Entity{createTime}
# 打印查询语句
logging:
  level:
    com:
      looedu:
        mapper: debug
server:
  servlet:
    port: 8080
#    context-path: /ss
# 加密
jasypt:
  encryptor:
    password: 123456